name: solvro_translator_with_drift_cache
description: A starting point for Dart libraries or applications.
version: 0.1.0
resolution: workspace
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  solvro_config: ^1.0.1
  test: ^1.24.0
