name: solvro_translator

packages:
  - packages/solvro_translatable
  - packages/solvro_translatable_generator
  - packages/solvro_translator_with_drift_cache

scripts:
  generate:
    run: melos exec -c 1 --depends-on build_runner -- dart run build_runner build
