name: solvro_translator
publish_to: none
environment:
  sdk: ^3.12.0

workspace:
  - packages/solvro_translator_generator
  - packages/solvro_translator_core
  - packages/solvro_translator_with_drift_cache_flutter

dev_dependencies:
  melos: 7.8.1
  solvro_config: 1.8.2-dev.1

lint_staged:
  "lib/**.dart": dart format && dart fix --apply
