name: solvro_translator
publish_to: none
environment:
  sdk: ^3.7.0

workspace:
  - packages/solvro_translator_generator
  - packages/solvro_translator_core
  - packages/solvro_translator_with_drift_cache

dev_dependencies:
  melos: 7.0.0-dev.8
  solvro_config: ^1.0.1

dependency_overrides:
  pub_updater: ^0.5.0

lint_staged:
  "lib/**.dart": dart format && dart fix --apply
