name: solvro_translator
publish_to: none
environment:
  sdk: ^3.7.0
workspace:
  - packages/solvro_translatable
  - packages/solvro_translatable_generator
  - packages/solvro_translator_with_drift_cache
