name: solvro_translator
publish_to: none
environment:
  sdk: ^3.8.0

workspace:
  - packages/solvro_translator_generator
  - packages/solvro_translator_core
  - packages/solvro_translator_with_drift_cache_flutter

dev_dependencies:
  melos: 7.0.0-dev.9
  solvro_config: ^1.0.1

lint_staged:
  "lib/**.dart": dart format && dart fix --apply
