name: solvro_translator_with_drift_cache_flutter
description: Solvro Translator client with drift cache
resolution: workspace
repository: https://github.com/solvro/lib-mobile-translator
version: "0.11.1"

environment:
  sdk: ^3.12.0
  flutter: ">=3.44.1"

dependencies:
  flutter:
    sdk: flutter
  solvro_translator_core: ^0.11.1
  freezed_annotation: ^3.1.0
  json_annotation: ^4.12.0
  dio: ^5.9.2
  drift: ^2.34.0
  drift_flutter: ^0.3.0
  path_provider: ^2.1.6

dev_dependencies:
  solvro_config: 1.9.0
  build_runner: ^2.15.0
  freezed: ^3.2.5
  json_serializable: ^6.14.0
  drift_dev: ^2.33.0
