name: solvro_translator_core
description: Core package for Solvro Translator with annotations, types and pure logic
version: 0.5.0
resolution: workspace
repository: https://github.com/Solvro/lib-mobile-translator

environment:
  sdk: ^3.8.0

dependencies:
  crypto: ^3.0.6

dev_dependencies:
  solvro_config: ^1.0.1
  test: ^1.24.0
