name: solvro_translator_core
description: A starting point for Dart libraries or applications.
version: 0.1.0
resolution: workspace
repository: https://github.com/Solvro/lib-mobile-solvro-translator

environment:
  sdk: ^3.7.2

dev_dependencies:
  solvro_config: ^1.0.1
  test: ^1.24.0
