name: solvro_translator_core
description: Core package for Solvro Translator with annotations, types and pure logic
version: 0.11.0-dev
resolution: workspace
repository: https://github.com/Solvro/lib-mobile-translator

environment:
  sdk: ^3.12.0

dependencies:
  crypto: ^3.0.7

dev_dependencies:
  solvro_config: 1.8.1-dev.1
