name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          
      - run: flutter --version

      - name: Install dependencies
        run: |
          flutter pub global activate melos
          flutter pub get
          melos bootstrap

      - name: Remove lib/l10n directory
        run: melos exec -- rm -rf lib/l10n/*.dart || true
        
      - name: Verify formatting
        run: melos exec -- dart format --output=none --set-exit-if-changed .
      
      - name: Regenerate the localization files
        run: melos exec -- flutter gen-l10n || true


      - name: Analyze project source
        run: melos exec -- flutter analyze --fatal-infos

      - name: Run custom lints
        run: melos exec -- dart run custom_lint --fatal-infos

