name: PR Title Check
on:
  pull_request:
    branches: [ "main" ]
    types: [opened, synchronize]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: "stable"
          
      - run: dart --version

      - name: Install dependencies
        run: dart pub get

      - name: Validate Title of PR
        run: echo "${{github.event.pull_request.title}}" | dart run commitlint_cli
  